addons:
  apt:
    packages:
    - python-pygments
sudo: true
dist: trusty
install:
- sudo apt-get --yes install snapd
- sudo snap install hugo
- rm -rf public || exit 0
script:
- "/snap/bin/hugo"
deploy:
  provider: s3
  access_key_id: AKIAJWPS2S6AZREF6A3Q
  secret_access_key:
    secure: HfPD5XoF5+SUMDGegayHAc/NrInfH36ABqrLaiNvksC6GyJ1kI/SWCoQkrvuyt4/qEtFETuorlDdwsE6aVxQcISW0NkKHVqMCrjnmlxWBLqrlJ8BUYoTCyR3cdw9BgYXuqI05+xGSZUMTVORG6jVuNDNWz0y15zNI4A4RLEGBRZrUdsXTslUd3cPLT3oTzJNRyRwU7NwiArtXMUXmAArs9v1qE+a7ARHkaYcBMuFyks20HXIbkzqL+Ur0631s+b10Vt6Y1B4YrylHu+8to/F1rhMq1MN5eRkjQwN8lDdMo3IAzY8/rutstxkMuzieOngzkNuA7MMltVvV7ijrIs3sNhXChnzjNnW+AMWvbsvncWOTRMbFA561s9zOe9hIfxei7VXtdIHfuRPmat7+1uEt8lJbBBbQlZjY0j2vRwNLuUfbp+ho5G3lvso4ubgohKp54lWAY8GNUHbp9qsuFFVCSrOhVtWOVKXcSsf0/391s661ZDqGwUKfc2EnlXkWRmcwX7E9mIqgWqjmf5HXto66U8XLc1cY58UOKxewKXcs7FNMxT5X/PowrBCa9XylNT3MmKg4/oNHlVrDphm3mHj3vEEuO6bRSkHbbmSODdvhQ72G8sJNqJpAwYPAJxtnP3e3sPjBJeBIiX4wwUJLbiABzwpV+SeU+/i+SMTWBAQnTA=
  bucket: internationalcafe
  local-dir: ./public
  upload-dir: siteroot
  acl: public_read
  on:
    repo: tomduckering/internationalcafe
